//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eWaySharedMethod
{
    using System;
    using System.Collections.Generic;
    
    public partial class BillingExtra
    {
        public int Id { get; set; }
        public int BillingId { get; set; }
        public int ItemCodeId { get; set; }
        public int TrackingCatOptId { get; set; }
        public decimal Amount { get; set; }
        public string Description { get; set; }
        public System.DateTime PeriodStart { get; set; }
        public System.DateTime PeriodEnd { get; set; }
        public string PaymentFrequency { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public string UpdatedBy { get; set; }
        public System.DateTime UpdatedOn { get; set; }
        public bool IsActive { get; set; }
        public byte[] Version { get; set; }
    
        public virtual Billing Billing { get; set; }
        public virtual XeroItemCode XeroItemCode { get; set; }
        public virtual XeroTrackingCatOption XeroTrackingCatOption { get; set; }
    }
}
