//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eWaySharedMethod
{
    using System;
    using System.Collections.Generic;
    
    public partial class BookingTemplateQueue
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BookingTemplateQueue()
        {
            this.BookingTemplateQueue_Child = new HashSet<BookingTemplateQueue_Child>();
        }
    
        public int Id { get; set; }
        public int BookingTemplateId { get; set; }
        public int UserId { get; set; }
        public int PaymentOptionId { get; set; }
        public Nullable<bool> IncludePastBookings { get; set; }
        public Nullable<bool> OscarIntended { get; set; }
        public bool IsProcessed { get; set; }
        public Nullable<System.DateTime> ProcessedOn { get; set; }
        public string Error { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public string CreatedBy { get; set; }
        public string ParentNotes { get; set; }
    
        public virtual BookingTemplate BookingTemplate { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BookingTemplateQueue_Child> BookingTemplateQueue_Child { get; set; }
        public virtual Lookup Lookup { get; set; }
        public virtual User User { get; set; }
    }
}
