//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eWaySharedMethod
{
    using System;
    using System.Collections.Generic;
    
    public partial class BookingHistoryLookup
    {
        public int Id { get; set; }
        public string CallerName { get; set; }
        public string Description { get; set; }
        public bool ShowInBookingHistory { get; set; }
    }
}
