//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eWaySharedMethod
{
    using System;
    using System.Collections.Generic;
    
    public partial class BookingView
    {
        public int Id { get; set; }
        public Nullable<int> BookingId { get; set; }
        public Nullable<int> SptId { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<int> ItemCodeId { get; set; }
        public Nullable<int> TrackingCodeId { get; set; }
        public int Expr1 { get; set; }
        public int BillingId { get; set; }
        public Nullable<int> Expr2 { get; set; }
        public int GuardianId { get; set; }
        public int ProgramCategoryId { get; set; }
        public int SiteId { get; set; }
        public int ChildId { get; set; }
        public Nullable<int> TrackingCatOptId { get; set; }
        public Nullable<int> BookingTypeId { get; set; }
        public string Status { get; set; }
        public Nullable<System.DateTime> WhenBooked { get; set; }
        public string Comment { get; set; }
        public bool IsActive { get; set; }
        public System.DateTime Expr3 { get; set; }
        public System.DateTime UpdatedOn { get; set; }
        public string Expr4 { get; set; }
        public string UpdatedBy { get; set; }
        public byte[] Version { get; set; }
        public int Expr5 { get; set; }
        public int UserId { get; set; }
        public int Expr6 { get; set; }
        public Nullable<int> PromoCodeId { get; set; }
        public Nullable<int> PaymentOptionId { get; set; }
        public Nullable<int> TermId { get; set; }
        public string Description { get; set; }
        public Nullable<decimal> OriginalCost { get; set; }
        public Nullable<decimal> EstimatedCost { get; set; }
        public Nullable<decimal> FinalCost { get; set; }
        public Nullable<decimal> EstimatedOscar { get; set; }
        public Nullable<bool> HasSentToXero { get; set; }
        public Nullable<decimal> PromoAmount { get; set; }
        public Nullable<decimal> PromoPercentage { get; set; }
        public System.DateTime Expr7 { get; set; }
        public string Expr8 { get; set; }
        public System.DateTime Expr9 { get; set; }
        public string Expr10 { get; set; }
        public bool Expr11 { get; set; }
        public byte[] Expr12 { get; set; }
        public string Name { get; set; }
        public Nullable<int> BookingTemplateId { get; set; }
        public int Expr13 { get; set; }
        public string Expr14 { get; set; }
        public Nullable<int> ParentSptId { get; set; }
        public int Expr15 { get; set; }
        public int Expr16 { get; set; }
        public Nullable<int> ProgramId { get; set; }
        public Nullable<int> ManagerId { get; set; }
        public Nullable<int> Expr17 { get; set; }
        public string Expr18 { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<int> Year { get; set; }
        public Nullable<System.DateTime> DateStart { get; set; }
        public Nullable<System.DateTime> DateEnd { get; set; }
        public Nullable<System.TimeSpan> TimeStart1 { get; set; }
        public Nullable<System.TimeSpan> TimeStart2 { get; set; }
        public Nullable<System.TimeSpan> TimeStart3 { get; set; }
        public Nullable<System.TimeSpan> TimeStart4 { get; set; }
        public Nullable<System.TimeSpan> TimeStart5 { get; set; }
        public Nullable<System.TimeSpan> TimeStart6 { get; set; }
        public Nullable<System.TimeSpan> TimeEnd1 { get; set; }
        public Nullable<System.TimeSpan> TimeEnd2 { get; set; }
        public Nullable<System.TimeSpan> TimeEnd3 { get; set; }
        public Nullable<System.TimeSpan> TimeEnd4 { get; set; }
        public Nullable<System.TimeSpan> TimeEnd5 { get; set; }
        public Nullable<System.TimeSpan> TimeEnd6 { get; set; }
        public Nullable<decimal> RateFullTime { get; set; }
        public Nullable<decimal> RatePartTime { get; set; }
        public Nullable<decimal> RateCasual { get; set; }
        public Nullable<decimal> Rate1 { get; set; }
        public Nullable<decimal> Rate2 { get; set; }
        public Nullable<decimal> Rate3 { get; set; }
        public Nullable<decimal> Rate4 { get; set; }
        public Nullable<decimal> Rate5 { get; set; }
        public Nullable<decimal> Rate6 { get; set; }
        public Nullable<int> MinAge { get; set; }
        public Nullable<int> MaxAge { get; set; }
        public System.DateTime Expr19 { get; set; }
        public System.DateTime Expr20 { get; set; }
        public string Expr21 { get; set; }
        public string Expr22 { get; set; }
        public bool Expr23 { get; set; }
        public Nullable<bool> Published { get; set; }
        public Nullable<System.DateTime> PublishedDate { get; set; }
        public byte[] Expr24 { get; set; }
        public string ImgURL { get; set; }
        public string TimeName1 { get; set; }
        public string TimeName2 { get; set; }
        public string TimeName3 { get; set; }
        public string TimeName4 { get; set; }
        public string TimeName5 { get; set; }
        public string TimeName6 { get; set; }
        public string TimeDescription1 { get; set; }
        public string TimeDescription2 { get; set; }
        public string TimeDescription3 { get; set; }
        public string TimeDescription4 { get; set; }
        public string TimeDescription5 { get; set; }
        public string TimeDescription6 { get; set; }
        public Nullable<int> Index { get; set; }
        public Nullable<int> FullTimeItemCodeId { get; set; }
        public Nullable<int> PartTimeItemCodeId { get; set; }
        public Nullable<int> CasualItemCodeId { get; set; }
        public Nullable<int> HolFullTimeItemCodeId { get; set; }
        public Nullable<int> HolPartTimeAMItemCodeId { get; set; }
        public Nullable<int> HolPartTimePMItemCodeId { get; set; }
        public Nullable<int> HolShortItemCodeId { get; set; }
        public Nullable<int> HolTripItemCodeId { get; set; }
        public Nullable<int> TrackingCatOptionId { get; set; }
        public Nullable<int> SpecialItemCodeId { get; set; }
    }
}
