//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eWaySharedMethod
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChildDiscountHistoryLookup
    {
        public int Id { get; set; }
        public int ChildDiscId { get; set; }
        public int BookingId { get; set; }
        public int BillingId { get; set; }
        public int InvoiceLineId { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime UpdatedOn { get; set; }
        public string UpdatedBy { get; set; }
        public bool IsActive { get; set; }
        public byte[] Version { get; set; }
    
        public virtual Billing Billing { get; set; }
        public virtual Booking Booking { get; set; }
        public virtual ChildDiscount ChildDiscount { get; set; }
        public virtual InvoiceLine InvoiceLine { get; set; }
    }
}
