//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eWaySharedMethod
{
    using System;
    using System.Collections.Generic;
    
    public partial class CreditNote
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CreditNote()
        {
            this.CreditNote_LineItem = new HashSet<CreditNote_LineItem>();
            this.XeroCreditNoteQueues = new HashSet<XeroCreditNoteQueue>();
        }
    
        public int Id { get; set; }
        public Nullable<int> BillingId { get; set; }
        public Nullable<System.Guid> XeroTransactionId { get; set; }
        public int StatusId { get; set; }
        public System.DateTime PaymentDate { get; set; }
        public string PaymentType { get; set; }
        public string Description { get; set; }
        public decimal Amount { get; set; }
        public string ErrorDescription { get; set; }
        public bool Error { get; set; }
        public string Email { get; set; }
        public Nullable<System.DateTime> XeroUpdatedDateUTC { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public string UpdatedBy { get; set; }
        public System.DateTime UpdatedOn { get; set; }
        public bool IsActive { get; set; }
        public byte[] Version { get; set; }
    
        public virtual Billing Billing { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CreditNote_LineItem> CreditNote_LineItem { get; set; }
        public virtual Lookup Lookup { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<XeroCreditNoteQueue> XeroCreditNoteQueues { get; set; }
    }
}
