//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eWaySharedMethod
{
    using System;
    using System.Collections.Generic;
    
    public partial class CssBillingPlanDetail
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CssBillingPlanDetail()
        {
            this.CssSubscriptions = new HashSet<CssSubscription>();
        }
    
        public int Id { get; set; }
        public int PlanId { get; set; }
        public int BillingRuleId { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public Nullable<int> Percentage { get; set; }
        public string Description { get; set; }
        public Nullable<System.DateTime> StarteDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public string UpdatedBy { get; set; }
        public bool IsActive { get; set; }
        public byte[] Version { get; set; }
    
        public virtual CssBillingPlan CssBillingPlan { get; set; }
        public virtual CssBillingRule CssBillingRule { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CssSubscription> CssSubscriptions { get; set; }
    }
}
