//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eWaySharedMethod
{
    using System;
    using System.Collections.Generic;
    
    public partial class CssBilling
    {
        public int Id { get; set; }
        public int SubscriptionId { get; set; }
        public System.DateTime BillingStartDate { get; set; }
        public System.DateTime BillingEndDate { get; set; }
        public string Status { get; set; }
        public Nullable<System.DateTime> PaidOn { get; set; }
        public string PaidBy { get; set; }
        public string PaymentStatus { get; set; }
        public bool IsActive { get; set; }
        public string Error { get; set; }
    
        public virtual CssSubscription CssSubscription { get; set; }
    }
}
