//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eWaySharedMethod
{
    using System;
    using System.Collections.Generic;
    
    public partial class CssInvoiceLine
    {
        public int Id { get; set; }
        public int InvoiceId { get; set; }
        public string ItemCode { get; set; }
        public string Description { get; set; }
        public Nullable<int> Quantity { get; set; }
        public decimal UnitPrice { get; set; }
        public string Account { get; set; }
        public decimal Amount { get; set; }
        public string TaxRate { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime UpdatedOn { get; set; }
        public string UpdatedBy { get; set; }
        public bool IsActive { get; set; }
        public byte[] Version { get; set; }
    
        public virtual CssInvoice CssInvoice { get; set; }
    }
}
