//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eWaySharedMethod
{
    using System;
    using System.Collections.Generic;
    
    public partial class CssSetting
    {
        public int Id { get; set; }
        public string XeroConsumerKey { get; set; }
        public Nullable<int> BillingAccountCode { get; set; }
        public Nullable<bool> isActive { get; set; }
        public string createdBy { get; set; }
        public Nullable<System.DateTime> createdOn { get; set; }
        public string updatedBy { get; set; }
        public Nullable<System.DateTime> updatedOn { get; set; }
        public byte[] Version { get; set; }
        public Nullable<int> BillingMethod { get; set; }
        public Nullable<decimal> SMSCharge { get; set; }
    }
}
