//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eWaySharedMethod
{
    using System;
    using System.Collections.Generic;
    
    public partial class FlyerTemplate
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public Nullable<int> SiteId { get; set; }
        public string FileName { get; set; }
        public string NewFileName { get; set; }
        public Nullable<int> MinItemCount { get; set; }
        public Nullable<int> MaxItemCount { get; set; }
        public bool IsActive { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime UpdatedOn { get; set; }
        public string UpdatedBy { get; set; }
        public byte[] Version { get; set; }
    
        public virtual Org Org { get; set; }
    }
}
