//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eWaySharedMethod
{
    using System;
    using System.Collections.Generic;
    
    public partial class HeadCountLine
    {
        public int Id { get; set; }
        public Nullable<int> HeadCountId { get; set; }
        public Nullable<int> ChildId { get; set; }
        public string ChildName { get; set; }
        public string ChildPhoto { get; set; }
        public Nullable<int> AttendanceId { get; set; }
        public bool IsAccounted { get; set; }
        public string Notes { get; set; }
        public string SiteGroups { get; set; }
        public Nullable<int> DayIndex { get; set; }
        public bool IsActive { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime UpdatedOn { get; set; }
        public string UpdatedBy { get; set; }
        public byte[] Version { get; set; }
    
        public virtual Attendance Attendance { get; set; }
        public virtual HeadCount HeadCount { get; set; }
    }
}
