//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eWaySharedMethod
{
    using System;
    using System.Collections.Generic;
    
    public partial class Medium
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Medium()
        {
            this.Child_Media = new HashSet<Child_Media>();
            this.Program_Media = new HashSet<Program_Media>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string EntityType { get; set; }
        public Nullable<int> EntityId { get; set; }
        public Nullable<int> SiteId { get; set; }
        public Nullable<int> MediaTypeId { get; set; }
        public string Description { get; set; }
        public string NewFileName { get; set; }
        public string OldFileName { get; set; }
        public string Url { get; set; }
        public Nullable<bool> IsProfilePicture { get; set; }
        public Nullable<bool> IsMedicalPdf { get; set; }
        public bool IsActive { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public string UpdatedBy { get; set; }
        public System.DateTime UpdatedOn { get; set; }
        public byte[] Version { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Child_Media> Child_Media { get; set; }
        public virtual Lookup Lookup { get; set; }
        public virtual Org Org { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Program_Media> Program_Media { get; set; }
    }
}
