//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eWaySharedMethod
{
    using System;
    using System.Collections.Generic;
    
    public partial class NotificationInstance
    {
        public int Id { get; set; }
        public int NotificationId { get; set; }
        public int OrgId { get; set; }
        public Nullable<int> UserId { get; set; }
        public string Subject { get; set; }
        public int ModuleId { get; set; }
        public string Message { get; set; }
        public string Attachment { get; set; }
        public string Error { get; set; }
        public Nullable<int> RetryCount { get; set; }
        public Nullable<bool> EmailProcessed { get; set; }
        public Nullable<bool> SMSProcessed { get; set; }
        public string Source { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public string CreatedBy { get; set; }
        public bool IsProcessed { get; set; }
    
        public virtual Notification Notification { get; set; }
        public virtual User User { get; set; }
        public virtual Org Org { get; set; }
    }
}
