//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eWaySharedMethod
{
    using System;
    using System.Collections.Generic;
    
    public partial class OscarSetting
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public OscarSetting()
        {
            this.User_OscarSetting = new HashSet<User_OscarSetting>();
        }
    
        public int Id { get; set; }
        public int OrgId { get; set; }
        public string ProgramManagerName { get; set; }
        public string ProgramMangerPhone { get; set; }
        public string ProgramManagerEmail { get; set; }
        public string Signature { get; set; }
        public Nullable<bool> UseDefaultEmails { get; set; }
        public string OscarApplicationRequestEmail { get; set; }
        public string OscarApplicationApproval { get; set; }
        public string OscarApplicationDeclined { get; set; }
        public string OscarDeclarationRequest { get; set; }
        public string OscarDeclarationApproval { get; set; }
        public string OscarDeclarationDeclined { get; set; }
        public string OscarDeclaration4WeeksOut { get; set; }
        public string OscarDeclaration3WeeksOut { get; set; }
        public string OscarDeclaration2WeeksOut { get; set; }
        public string OscarDeclaration1WeeksOut { get; set; }
        public string OscarCOCRequest { get; set; }
        public string OscarRenewalRequest { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public string UpdatedBy { get; set; }
        public bool IsActive { get; set; }
    
        public virtual Org Org { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<User_OscarSetting> User_OscarSetting { get; set; }
    }
}
