//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eWaySharedMethod
{
    using System;
    using System.Collections.Generic;
    
    public partial class PaymentBatch
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PaymentBatch()
        {
            this.Payments = new HashSet<Payment>();
        }
    
        public int Id { get; set; }
        public string PaymentReference { get; set; }
        public int PayerId { get; set; }
        public string PayerReference { get; set; }
        public Nullable<int> SiteId { get; set; }
        public Nullable<int> TransactionId { get; set; }
        public string Email { get; set; }
        public string PaymentType { get; set; }
        public decimal Amount { get; set; }
        public System.DateTime PaidOn { get; set; }
        public string Status { get; set; }
        public bool IsActive { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public string ResponseMessage { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime UpdatedOn { get; set; }
        public string UpdatedBy { get; set; }
        public byte[] Version { get; set; }
        public string AccessCode { get; set; }
        public string Errors { get; set; }
        public Nullable<int> PaymentMethodId { get; set; }
        public string PaidBy { get; set; }
    
        public virtual Lookup Lookup { get; set; }
        public virtual Org Org { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Payment> Payments { get; set; }
        public virtual User User { get; set; }
    }
}
