//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eWaySharedMethod
{
    using System;
    using System.Collections.Generic;
    
    public partial class School_Org
    {
        public int Id { get; set; }
        public int OrgId { get; set; }
        public int SchoolId { get; set; }
        public string Notes { get; set; }
        public string PickUpLocation { get; set; }
        public bool CanPickUp { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public string CreatedBy { get; set; }
    
        public virtual Org Org { get; set; }
        public virtual School School { get; set; }
    }
}
