//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eWaySharedMethod
{
    using System;
    using System.Collections.Generic;
    
    public partial class Site_Program_Term
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Site_Program_Term()
        {
            this.ActivityInstances = new HashSet<ActivityInstance>();
            this.Booking_Spt = new HashSet<Booking_Spt>();
            this.OscarDelaration_Child = new HashSet<OscarDelaration_Child>();
            this.Site_Program_Term1 = new HashSet<Site_Program_Term>();
            this.Spt_ExcludeDays = new HashSet<Spt_ExcludeDays>();
            this.Spt_Instance = new HashSet<Spt_Instance>();
            this.Spt_Session = new HashSet<Spt_Session>();
            this.Spt_SiteGroup = new HashSet<Spt_SiteGroup>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public Nullable<int> ParentSptId { get; set; }
        public int SiteId { get; set; }
        public int TermId { get; set; }
        public Nullable<int> ProgramId { get; set; }
        public Nullable<int> ManagerId { get; set; }
        public Nullable<int> ProgramCategoryId { get; set; }
        public string Description { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<int> Year { get; set; }
        public Nullable<System.DateTime> DateStart { get; set; }
        public Nullable<System.DateTime> DateEnd { get; set; }
        public Nullable<System.TimeSpan> TimeStart1 { get; set; }
        public Nullable<System.TimeSpan> TimeStart2 { get; set; }
        public Nullable<System.TimeSpan> TimeStart3 { get; set; }
        public Nullable<System.TimeSpan> TimeStart4 { get; set; }
        public Nullable<System.TimeSpan> TimeStart5 { get; set; }
        public Nullable<System.TimeSpan> TimeStart6 { get; set; }
        public Nullable<System.TimeSpan> TimeEnd1 { get; set; }
        public Nullable<System.TimeSpan> TimeEnd2 { get; set; }
        public Nullable<System.TimeSpan> TimeEnd3 { get; set; }
        public Nullable<System.TimeSpan> TimeEnd4 { get; set; }
        public Nullable<System.TimeSpan> TimeEnd5 { get; set; }
        public Nullable<System.TimeSpan> TimeEnd6 { get; set; }
        public Nullable<decimal> RateFullTime { get; set; }
        public Nullable<decimal> RatePartTime { get; set; }
        public Nullable<decimal> RateCasual { get; set; }
        public Nullable<decimal> Rate1 { get; set; }
        public Nullable<decimal> Rate2 { get; set; }
        public Nullable<decimal> Rate3 { get; set; }
        public Nullable<decimal> Rate4 { get; set; }
        public Nullable<decimal> Rate5 { get; set; }
        public Nullable<decimal> Rate6 { get; set; }
        public Nullable<int> MinAge { get; set; }
        public Nullable<int> MaxAge { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public System.DateTime UpdatedOn { get; set; }
        public string CreatedBy { get; set; }
        public string UpdatedBy { get; set; }
        public bool IsActive { get; set; }
        public Nullable<bool> Published { get; set; }
        public Nullable<System.DateTime> PublishedDate { get; set; }
        public byte[] Version { get; set; }
        public string ImgURL { get; set; }
        public string TimeName1 { get; set; }
        public string TimeName2 { get; set; }
        public string TimeName3 { get; set; }
        public string TimeName4 { get; set; }
        public string TimeName5 { get; set; }
        public string TimeName6 { get; set; }
        public string TimeDescription1 { get; set; }
        public string TimeDescription2 { get; set; }
        public string TimeDescription3 { get; set; }
        public string TimeDescription4 { get; set; }
        public string TimeDescription5 { get; set; }
        public string TimeDescription6 { get; set; }
        public Nullable<int> Index { get; set; }
        public Nullable<int> FullTimeItemCodeId { get; set; }
        public Nullable<int> PartTimeItemCodeId { get; set; }
        public Nullable<int> CasualItemCodeId { get; set; }
        public Nullable<int> HolFullTimeItemCodeId { get; set; }
        public Nullable<int> HolPartTimeAMItemCodeId { get; set; }
        public Nullable<int> HolPartTimePMItemCodeId { get; set; }
        public Nullable<int> HolShortItemCodeId { get; set; }
        public Nullable<int> HolTripItemCodeId { get; set; }
        public Nullable<int> TrackingCatOptionId { get; set; }
        public Nullable<int> SpecialItemCodeId { get; set; }
        public Nullable<bool> IsFullDay { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ActivityInstance> ActivityInstances { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Booking_Spt> Booking_Spt { get; set; }
        public virtual Org Org { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OscarDelaration_Child> OscarDelaration_Child { get; set; }
        public virtual Program Program { get; set; }
        public virtual ProgramCategory ProgramCategory { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Site_Program_Term> Site_Program_Term1 { get; set; }
        public virtual Site_Program_Term Site_Program_Term2 { get; set; }
        public virtual Term Term { get; set; }
        public virtual User User { get; set; }
        public virtual XeroItemCode XeroItemCode { get; set; }
        public virtual XeroItemCode XeroItemCode1 { get; set; }
        public virtual XeroItemCode XeroItemCode2 { get; set; }
        public virtual XeroItemCode XeroItemCode3 { get; set; }
        public virtual XeroItemCode XeroItemCode4 { get; set; }
        public virtual XeroItemCode XeroItemCode5 { get; set; }
        public virtual XeroItemCode XeroItemCode6 { get; set; }
        public virtual XeroItemCode XeroItemCode7 { get; set; }
        public virtual XeroItemCode XeroItemCode8 { get; set; }
        public virtual XeroTrackingCatOption XeroTrackingCatOption { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Spt_ExcludeDays> Spt_ExcludeDays { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Spt_Instance> Spt_Instance { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Spt_Session> Spt_Session { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Spt_SiteGroup> Spt_SiteGroup { get; set; }
    }
}
