//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eWaySharedMethod
{
    using System;
    using System.Collections.Generic;
    
    public partial class Spt_Instance
    {
        public int Id { get; set; }
        public Nullable<int> SptId { get; set; }
        public Nullable<int> ClassId { get; set; }
        public Nullable<int> StaffId { get; set; }
        public Nullable<bool> IsFullDay { get; set; }
        public Nullable<decimal> Cost { get; set; }
        public Nullable<int> SiteId { get; set; }
        public Nullable<int> TermId { get; set; }
        public Nullable<int> Capacity { get; set; }
        public System.DateTime StartDateTime { get; set; }
        public System.DateTime EndDateTime { get; set; }
        public Nullable<int> Duration { get; set; }
        public string RecurrenceType { get; set; }
        public Nullable<int> RecurrenceId { get; set; }
        public string RecurrenceException { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime UpdatedOn { get; set; }
        public string UpdatedBy { get; set; }
        public byte[] Version { get; set; }
        public bool IsActive { get; set; }
    
        public virtual Org Org { get; set; }
        public virtual Program Program { get; set; }
        public virtual Site_Program_Term Site_Program_Term { get; set; }
        public virtual Term Term { get; set; }
    }
}
