//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eWaySharedMethod
{
    using System;
    using System.Collections.Generic;
    
    public partial class Spt_SiteGroup
    {
        public int Id { get; set; }
        public int SptId { get; set; }
        public int SiteGroupId { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public string CreatedBy { get; set; }
    
        public virtual Site_Program_Term Site_Program_Term { get; set; }
        public virtual SiteGroup SiteGroup { get; set; }
    }
}
