//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eWaySharedMethod
{
    using System;
    using System.Collections.Generic;
    
    public partial class StaffRoster
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public StaffRoster()
        {
            this.ActivityInstance_Staff = new HashSet<ActivityInstance_Staff>();
            this.StaffClockSignatures = new HashSet<StaffClockSignature>();
            this.StaffRoster1 = new HashSet<StaffRoster>();
            this.StaffRosterHistories = new HashSet<StaffRosterHistory>();
        }
    
        public int Id { get; set; }
        public int StaffId { get; set; }
        public int OrgId { get; set; }
        public System.DateTime StartDate { get; set; }
        public System.DateTime EndDate { get; set; }
        public string Description { get; set; }
        public Nullable<bool> IsSingle { get; set; }
        public Nullable<int> ParentId { get; set; }
        public Nullable<decimal> SalaryCost { get; set; }
        public bool HasAttended { get; set; }
        public bool IsActive { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public System.DateTime UpdatedOn { get; set; }
        public string CreatedBy { get; set; }
        public string UpdatedBy { get; set; }
        public byte[] Version { get; set; }
        public Nullable<System.DateTime> ClockIn { get; set; }
        public Nullable<System.DateTime> ClockOut { get; set; }
        public Nullable<decimal> Lat { get; set; }
        public Nullable<decimal> Long { get; set; }
        public string ClockInMethod { get; set; }
        public string ClockOutMethod { get; set; }
        public Nullable<int> TimeSheetId { get; set; }
        public string Reference { get; set; }
        public string Notes { get; set; }
        public bool IsProcessed { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ActivityInstance_Staff> ActivityInstance_Staff { get; set; }
        public virtual Org Org { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StaffClockSignature> StaffClockSignatures { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StaffRoster> StaffRoster1 { get; set; }
        public virtual StaffRoster StaffRoster2 { get; set; }
        public virtual User User { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StaffRosterHistory> StaffRosterHistories { get; set; }
        public virtual TimeSheet TimeSheet { get; set; }
    }
}
