//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eWaySharedMethod
{
    using System;
    using System.Collections.Generic;
    
    public partial class XeroProcessorState
    {
        public int Id { get; set; }
        public Nullable<int> OrgId { get; set; }
        public System.DateTime LastUpdated { get; set; }
        public bool IsProcessed { get; set; }
        public string EntityType { get; set; }
        public string XeroConsumerKey { get; set; }
        public Nullable<bool> Error { get; set; }
        public string ErrorDescription { get; set; }
    
        public virtual Org Org { get; set; }
    }
}
