//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eWaySharedMethod
{
    using System;
    using System.Collections.Generic;
    
    public partial class XeroCSSInvoiceUpdateQueue
    {
        public int Id { get; set; }
        public Nullable<int> OrgId { get; set; }
        public Nullable<int> InvoiceId { get; set; }
        public Nullable<int> InvoiceItemId { get; set; }
        public bool IsProcessed { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
    
        public virtual CssInvoice CssInvoice { get; set; }
    }
}
