//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eWaySharedMethod
{
    using System;
    using System.Collections.Generic;
    
    public partial class XeroCSSInvoiceQueue
    {
        public int Id { get; set; }
        public int OrgId { get; set; }
        public int InvoiceId { get; set; }
        public bool IsProcessed { get; set; }
        public bool Error { get; set; }
        public string ErrorDescription { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public Nullable<System.DateTime> GenerateInvOn { get; set; }
    
        public virtual CssInvoice CssInvoice { get; set; }
    }
}
