//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eWaySharedMethod
{
    using System;
    using System.Collections.Generic;
    
    public partial class XeroInvoice
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public XeroInvoice()
        {
            this.XeroInvoiceLines = new HashSet<XeroInvoiceLine>();
        }
    
        public int Id { get; set; }
        public Nullable<int> UserId { get; set; }
        public int StatusId { get; set; }
        public string XeroConsumerKey { get; set; }
        public System.Guid XeroInvoiceId { get; set; }
        public string XeroInvoiceCode { get; set; }
        public string Email { get; set; }
        public string Reference { get; set; }
        public Nullable<decimal> Discount { get; set; }
        public Nullable<decimal> AmountDue { get; set; }
        public Nullable<decimal> AmountPaid { get; set; }
        public Nullable<decimal> AmountCredited { get; set; }
        public Nullable<decimal> TotalAmount { get; set; }
        public Nullable<System.DateTime> DueDate { get; set; }
        public Nullable<bool> Error { get; set; }
        public string ErrorDescription { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public System.DateTime UpdatedOn { get; set; }
    
        public virtual User User { get; set; }
        public virtual XeroLookup XeroLookup { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<XeroInvoiceLine> XeroInvoiceLines { get; set; }
    }
}
