//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eWaySharedMethod
{
    using System;
    using System.Collections.Generic;
    
    public partial class XeroInvErrorQueue
    {
        public int Id { get; set; }
        public int XeroInvQueueId { get; set; }
        public string XeroConsumerKey { get; set; }
        public string ErrorType { get; set; }
        public string ErrorDescription { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public System.DateTime UpdatedOn { get; set; }
        public bool IsProcessed { get; set; }
    
        public virtual XeroInvoiceQueue XeroInvoiceQueue { get; set; }
    }
}
