//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestEwayService
{
    using System;
    using System.Collections.Generic;
    
    public partial class Activity
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Activity()
        {
            this.Activity_Condition = new HashSet<Activity_Condition>();
            this.ActivityInstances = new HashSet<ActivityInstance>();
            this.ActivityItems = new HashSet<ActivityItem>();
            this.Ratings = new HashSet<Rating>();
        }
    
        public int Id { get; set; }
        public Nullable<int> CategoryId { get; set; }
        public Nullable<int> SiteId { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public Nullable<int> NoOfChild { get; set; }
        public Nullable<int> NoOfStaff { get; set; }
        public bool IsPrivate { get; set; }
        public Nullable<int> DurationMin { get; set; }
        public bool HasSaved { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public System.DateTime UpdatedOn { get; set; }
        public string CreatedBy { get; set; }
        public string UpdatedBy { get; set; }
        public bool IsActive { get; set; }
        public byte[] Version { get; set; }
        public string Review { get; set; }
        public Nullable<int> Rating { get; set; }
        public string Instruction { get; set; }
        public Nullable<decimal> Budget { get; set; }
        public Nullable<decimal> CostPerChild { get; set; }
        public Nullable<bool> IsFavourite { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Activity_Condition> Activity_Condition { get; set; }
        public virtual Lookup Lookup { get; set; }
        public virtual Org Org { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ActivityInstance> ActivityInstances { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ActivityItem> ActivityItems { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Rating> Ratings { get; set; }
    }
}
