//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestEwayService
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class AimyEntity : DbContext
    {
        public AimyEntity()
            : base("name=AimyEntity")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AchievementTracking> AchievementTrackings { get; set; }
        public virtual DbSet<Activity> Activities { get; set; }
        public virtual DbSet<Activity_Condition> Activity_Condition { get; set; }
        public virtual DbSet<ActivityInstance> ActivityInstances { get; set; }
        public virtual DbSet<ActivityInstance_Child> ActivityInstance_Child { get; set; }
        public virtual DbSet<ActivityInstance_Condition> ActivityInstance_Condition { get; set; }
        public virtual DbSet<ActivityInstance_Staff> ActivityInstance_Staff { get; set; }
        public virtual DbSet<ActivityItem> ActivityItems { get; set; }
        public virtual DbSet<AppliedDiscount> AppliedDiscounts { get; set; }
        public virtual DbSet<Attendance> Attendances { get; set; }
        public virtual DbSet<Attendance_Portfolio> Attendance_Portfolio { get; set; }
        public virtual DbSet<Audit> Audits { get; set; }
        public virtual DbSet<BatchTimeSheet> BatchTimeSheets { get; set; }
        public virtual DbSet<Billing> Billings { get; set; }
        public virtual DbSet<BillingDiscount> BillingDiscounts { get; set; }
        public virtual DbSet<BillingExtra> BillingExtras { get; set; }
        public virtual DbSet<Booking> Bookings { get; set; }
        public virtual DbSet<Booking_Spt> Booking_Spt { get; set; }
        public virtual DbSet<BookingAudit> BookingAudits { get; set; }
        public virtual DbSet<BookingHistoryLookup> BookingHistoryLookups { get; set; }
        public virtual DbSet<BookingTemplate> BookingTemplates { get; set; }
        public virtual DbSet<BookingTemplateQueue> BookingTemplateQueues { get; set; }
        public virtual DbSet<BookingTemplateQueue_Child> BookingTemplateQueue_Child { get; set; }
        public virtual DbSet<BookingTypeRule> BookingTypeRules { get; set; }
        public virtual DbSet<Child> Children { get; set; }
        public virtual DbSet<Child_Condition> Child_Condition { get; set; }
        public virtual DbSet<Child_Contact> Child_Contact { get; set; }
        public virtual DbSet<Child_Media> Child_Media { get; set; }
        public virtual DbSet<Child_Timeline> Child_Timeline { get; set; }
        public virtual DbSet<ChildDiscount> ChildDiscounts { get; set; }
        public virtual DbSet<ChildDiscountHistoryLookup> ChildDiscountHistoryLookups { get; set; }
        public virtual DbSet<ChildNote> ChildNotes { get; set; }
        public virtual DbSet<City> Cities { get; set; }
        public virtual DbSet<Condition> Conditions { get; set; }
        public virtual DbSet<Contact> Contacts { get; set; }
        public virtual DbSet<ContactGroup> ContactGroups { get; set; }
        public virtual DbSet<CopyDataOption> CopyDataOptions { get; set; }
        public virtual DbSet<Country> Countries { get; set; }
        public virtual DbSet<CreditNote> CreditNotes { get; set; }
        public virtual DbSet<CreditNote_LineItem> CreditNote_LineItem { get; set; }
        public virtual DbSet<CssBilling> CssBillings { get; set; }
        public virtual DbSet<CssBillingGroup> CssBillingGroups { get; set; }
        public virtual DbSet<CssBillingGroup_Org> CssBillingGroup_Org { get; set; }
        public virtual DbSet<CssBillingPlan> CssBillingPlans { get; set; }
        public virtual DbSet<CssBillingPlanDetail> CssBillingPlanDetails { get; set; }
        public virtual DbSet<CssBillingRule> CssBillingRules { get; set; }
        public virtual DbSet<CssCreditCardAccessCode> CssCreditCardAccessCodes { get; set; }
        public virtual DbSet<CssInvoice> CssInvoices { get; set; }
        public virtual DbSet<CssInvoiceLine> CssInvoiceLines { get; set; }
        public virtual DbSet<CssLookup> CssLookups { get; set; }
        public virtual DbSet<CssPaymentSetup> CssPaymentSetups { get; set; }
        public virtual DbSet<CssSetting> CssSettings { get; set; }
        public virtual DbSet<CssSubscription> CssSubscriptions { get; set; }
        public virtual DbSet<CssSysAdminUser> CssSysAdminUsers { get; set; }
        public virtual DbSet<DailyAttendance> DailyAttendances { get; set; }
        public virtual DbSet<DashboardMessage> DashboardMessages { get; set; }
        public virtual DbSet<DashboardViewHistory> DashboardViewHistories { get; set; }
        public virtual DbSet<DefaultBillingDiscount> DefaultBillingDiscounts { get; set; }
        public virtual DbSet<DefaultTerm> DefaultTerms { get; set; }
        public virtual DbSet<DeletingInvoiceQueue> DeletingInvoiceQueues { get; set; }
        public virtual DbSet<EventDuration> EventDurations { get; set; }
        public virtual DbSet<ExcludeDay> ExcludeDays { get; set; }
        public virtual DbSet<FinancialHistory> FinancialHistories { get; set; }
        public virtual DbSet<FlyerTemplate> FlyerTemplates { get; set; }
        public virtual DbSet<Form> Forms { get; set; }
        public virtual DbSet<FormField> FormFields { get; set; }
        public virtual DbSet<FormFieldValue> FormFieldValues { get; set; }
        public virtual DbSet<FormInstance> FormInstances { get; set; }
        public virtual DbSet<FormTemplate> FormTemplates { get; set; }
        public virtual DbSet<Guardian_Child> Guardian_Child { get; set; }
        public virtual DbSet<HeadCount> HeadCounts { get; set; }
        public virtual DbSet<HeadCountLine> HeadCountLines { get; set; }
        public virtual DbSet<ImpersonateUserHistory> ImpersonateUserHistories { get; set; }
        public virtual DbSet<Invoice> Invoices { get; set; }
        public virtual DbSet<InvoiceLine> InvoiceLines { get; set; }
        public virtual DbSet<InvoicePayment> InvoicePayments { get; set; }
        public virtual DbSet<Language> Languages { get; set; }
        public virtual DbSet<Lookup> Lookups { get; set; }
        public virtual DbSet<Medium> Media { get; set; }
        public virtual DbSet<MessageHistory> MessageHistories { get; set; }
        public virtual DbSet<Note> Notes { get; set; }
        public virtual DbSet<Notification> Notifications { get; set; }
        public virtual DbSet<Notification_User> Notification_User { get; set; }
        public virtual DbSet<NotificationInstance> NotificationInstances { get; set; }
        public virtual DbSet<NotificationReminder> NotificationReminders { get; set; }
        public virtual DbSet<Org> Orgs { get; set; }
        public virtual DbSet<Org_Child> Org_Child { get; set; }
        public virtual DbSet<Org_Contact> Org_Contact { get; set; }
        public virtual DbSet<Org_CSS_BillingRule> Org_CSS_BillingRule { get; set; }
        public virtual DbSet<Org_Testing_Subscription> Org_Testing_Subscription { get; set; }
        public virtual DbSet<Org_User> Org_User { get; set; }
        public virtual DbSet<OrgCustomize> OrgCustomizes { get; set; }
        public virtual DbSet<OrgDesign> OrgDesigns { get; set; }
        public virtual DbSet<OrgEmailBodyTemplate> OrgEmailBodyTemplates { get; set; }
        public virtual DbSet<OrgNotificationSetting> OrgNotificationSettings { get; set; }
        public virtual DbSet<OrgReference> OrgReferences { get; set; }
        public virtual DbSet<OrgReferenceSetting> OrgReferenceSettings { get; set; }
        public virtual DbSet<OrgSetting> OrgSettings { get; set; }
        public virtual DbSet<OrgTandC> OrgTandCs { get; set; }
        public virtual DbSet<OscarCoC> OscarCoCs { get; set; }
        public virtual DbSet<OscarDeclaration> OscarDeclarations { get; set; }
        public virtual DbSet<OscarDelaration_Child> OscarDelaration_Child { get; set; }
        public virtual DbSet<OscarRenewalFormTracking> OscarRenewalFormTrackings { get; set; }
        public virtual DbSet<OscarSetting> OscarSettings { get; set; }
        public virtual DbSet<OscarTracking> OscarTrackings { get; set; }
        public virtual DbSet<OscarTracking_Child> OscarTracking_Child { get; set; }
        public virtual DbSet<OutgoingMessage> OutgoingMessages { get; set; }
        public virtual DbSet<Payment> Payments { get; set; }
        public virtual DbSet<PaymentBatch> PaymentBatches { get; set; }
        public virtual DbSet<PaymentSource> PaymentSources { get; set; }
        public virtual DbSet<Permission> Permissions { get; set; }
        public virtual DbSet<Permission_User> Permission_User { get; set; }
        public virtual DbSet<PortfolioSetting> PortfolioSettings { get; set; }
        public virtual DbSet<Program> Programs { get; set; }
        public virtual DbSet<Program_Media> Program_Media { get; set; }
        public virtual DbSet<Program_Session> Program_Session { get; set; }
        public virtual DbSet<Program_Tags> Program_Tags { get; set; }
        public virtual DbSet<ProgramCategory> ProgramCategories { get; set; }
        public virtual DbSet<PromoCode> PromoCodes { get; set; }
        public virtual DbSet<PromoCodeUsage> PromoCodeUsages { get; set; }
        public virtual DbSet<PromoMsgTemplate> PromoMsgTemplates { get; set; }
        public virtual DbSet<PublicHoliday> PublicHolidays { get; set; }
        public virtual DbSet<QrCode> QrCodes { get; set; }
        public virtual DbSet<Rating> Ratings { get; set; }
        public virtual DbSet<Report> Reports { get; set; }
        public virtual DbSet<ReportPeriod> ReportPeriods { get; set; }
        public virtual DbSet<ReportSubscriber> ReportSubscribers { get; set; }
        public virtual DbSet<ReportSubscription> ReportSubscriptions { get; set; }
        public virtual DbSet<RollCallQueue> RollCallQueues { get; set; }
        public virtual DbSet<School> Schools { get; set; }
        public virtual DbSet<School_Contact> School_Contact { get; set; }
        public virtual DbSet<School_Org> School_Org { get; set; }
        public virtual DbSet<SelectedInvoice> SelectedInvoices { get; set; }
        public virtual DbSet<Session> Sessions { get; set; }
        public virtual DbSet<SessionDiscount> SessionDiscounts { get; set; }
        public virtual DbSet<SignoutSignature> SignoutSignatures { get; set; }
        public virtual DbSet<Site_PaymentOption> Site_PaymentOption { get; set; }
        public virtual DbSet<Site_Program_Term> Site_Program_Term { get; set; }
        public virtual DbSet<SiteDPSDetail> SiteDPSDetails { get; set; }
        public virtual DbSet<SiteGroup> SiteGroups { get; set; }
        public virtual DbSet<SiteGroup_Booking_Spt> SiteGroup_Booking_Spt { get; set; }
        public virtual DbSet<SiteNote> SiteNotes { get; set; }
        public virtual DbSet<SitePaymentGateway> SitePaymentGateways { get; set; }
        public virtual DbSet<SitePaymentMethod> SitePaymentMethods { get; set; }
        public virtual DbSet<Spt_ExcludeDays> Spt_ExcludeDays { get; set; }
        public virtual DbSet<Spt_Instance> Spt_Instance { get; set; }
        public virtual DbSet<Spt_Session> Spt_Session { get; set; }
        public virtual DbSet<Spt_SiteGroup> Spt_SiteGroup { get; set; }
        public virtual DbSet<StaffAvailability> StaffAvailabilities { get; set; }
        public virtual DbSet<StaffClock> StaffClocks { get; set; }
        public virtual DbSet<StaffClockSignature> StaffClockSignatures { get; set; }
        public virtual DbSet<StaffRoster> StaffRosters { get; set; }
        public virtual DbSet<StaffRosterHistory> StaffRosterHistories { get; set; }
        public virtual DbSet<Subsidy> Subsidies { get; set; }
        public virtual DbSet<SubsidyPayment> SubsidyPayments { get; set; }
        public virtual DbSet<SubsidyPaymentIndex> SubsidyPaymentIndexes { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<TempManualPayment> TempManualPayments { get; set; }
        public virtual DbSet<Term> Terms { get; set; }
        public virtual DbSet<Territory> Territories { get; set; }
        public virtual DbSet<Timeline> Timelines { get; set; }
        public virtual DbSet<TimeSheet> TimeSheets { get; set; }
        public virtual DbSet<tmpContact> tmpContacts { get; set; }
        public virtual DbSet<tmpImport> tmpImports { get; set; }
        public virtual DbSet<tmpUser_Contact> tmpUser_Contact { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<User_Child> User_Child { get; set; }
        public virtual DbSet<User_Contact> User_Contact { get; set; }
        public virtual DbSet<User_FavouriteSites> User_FavouriteSites { get; set; }
        public virtual DbSet<User_Message> User_Message { get; set; }
        public virtual DbSet<User_OscarSetting> User_OscarSetting { get; set; }
        public virtual DbSet<User_Permission> User_Permission { get; set; }
        public virtual DbSet<UserOrgAccess> UserOrgAccesses { get; set; }
        public virtual DbSet<XeroAccountCode> XeroAccountCodes { get; set; }
        public virtual DbSet<XeroContact> XeroContacts { get; set; }
        public virtual DbSet<XeroCreditNoteQueue> XeroCreditNoteQueues { get; set; }
        public virtual DbSet<XeroCSSAccountCode> XeroCSSAccountCodes { get; set; }
        public virtual DbSet<XeroCSSInvoiceQueue> XeroCSSInvoiceQueues { get; set; }
        public virtual DbSet<XeroCSSInvoiceUpdateQueue> XeroCSSInvoiceUpdateQueues { get; set; }
        public virtual DbSet<XeroEditBookingQueue> XeroEditBookingQueues { get; set; }
        public virtual DbSet<XeroEditInvoiceQueue> XeroEditInvoiceQueues { get; set; }
        public virtual DbSet<XeroInvErrorQueue> XeroInvErrorQueues { get; set; }
        public virtual DbSet<XeroInvoice> XeroInvoices { get; set; }
        public virtual DbSet<XeroInvoiceLine> XeroInvoiceLines { get; set; }
        public virtual DbSet<XeroInvoiceQueue> XeroInvoiceQueues { get; set; }
        public virtual DbSet<XeroItemCode> XeroItemCodes { get; set; }
        public virtual DbSet<XeroLookup> XeroLookups { get; set; }
        public virtual DbSet<XeroPaymentQueue> XeroPaymentQueues { get; set; }
        public virtual DbSet<XeroProcessorState> XeroProcessorStates { get; set; }
        public virtual DbSet<XeroSubsidyPaymentQueue> XeroSubsidyPaymentQueues { get; set; }
        public virtual DbSet<XeroTrackingCategory> XeroTrackingCategories { get; set; }
        public virtual DbSet<XeroTrackingCatOption> XeroTrackingCatOptions { get; set; }
        public virtual DbSet<AttendanceData> AttendanceDatas { get; set; }
        public virtual DbSet<School_Temporary> School_Temporary { get; set; }
        public virtual DbSet<StaffRosterStage> StaffRosterStages { get; set; }
    }
}
