//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestEwayService
{
    using System;
    using System.Collections.Generic;
    
    public partial class Attendance_Portfolio
    {
        public int Id { get; set; }
        public int PortfolioSettingId { get; set; }
        public int UserId { get; set; }
        public int AttendanceId { get; set; }
        public int ChildId { get; set; }
        public string Note { get; set; }
        public bool IsRead { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime UpdatedOn { get; set; }
        public int UpdatedBy { get; set; }
        public bool IsActive { get; set; }
    
        public virtual Attendance Attendance { get; set; }
        public virtual Child Child { get; set; }
        public virtual PortfolioSetting PortfolioSetting { get; set; }
        public virtual User User { get; set; }
    }
}
