//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestEwayService
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChildDiscount
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ChildDiscount()
        {
            this.AppliedDiscounts = new HashSet<AppliedDiscount>();
            this.ChildDiscountHistoryLookups = new HashSet<ChildDiscountHistoryLookup>();
            this.SessionDiscounts = new HashSet<SessionDiscount>();
        }
    
        public int Id { get; set; }
        public int ChildId { get; set; }
        public int ProgramCateogryId { get; set; }
        public Nullable<int> ProgramId { get; set; }
        public int SiteId { get; set; }
        public Nullable<decimal> FullTimeRate { get; set; }
        public Nullable<decimal> PartTimeRate { get; set; }
        public Nullable<decimal> CasualRate { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime UpdatedOn { get; set; }
        public string UpdatedBy { get; set; }
        public bool IsActive { get; set; }
        public byte[] Version { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AppliedDiscount> AppliedDiscounts { get; set; }
        public virtual Child Child { get; set; }
        public virtual Org Org { get; set; }
        public virtual Program Program { get; set; }
        public virtual ProgramCategory ProgramCategory { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChildDiscountHistoryLookup> ChildDiscountHistoryLookups { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SessionDiscount> SessionDiscounts { get; set; }
    }
}
