//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestEwayService
{
    using System;
    using System.Collections.Generic;
    
    public partial class CssBillingGroup
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CssBillingGroup()
        {
            this.CssBillingGroup1 = new HashSet<CssBillingGroup>();
            this.CssBillingGroup_Org = new HashSet<CssBillingGroup_Org>();
        }
    
        public int Id { get; set; }
        public Nullable<int> OrgId { get; set; }
        public Nullable<int> ParentGroupId { get; set; }
        public Nullable<int> UserId { get; set; }
        public string GroupName { get; set; }
        public string GroupDescription { get; set; }
        public bool IsActive { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public byte[] Version { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CssBillingGroup> CssBillingGroup1 { get; set; }
        public virtual CssBillingGroup CssBillingGroup2 { get; set; }
        public virtual Org Org { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CssBillingGroup_Org> CssBillingGroup_Org { get; set; }
    }
}
