//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestEwayService
{
    using System;
    using System.Collections.Generic;
    
    public partial class CssPaymentSetup
    {
        public int Id { get; set; }
        public int OrgId { get; set; }
        public string CustomerId { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public int CreatedBy { get; set; }
        public string MaskedCardNumber { get; set; }
        public string CreditCardType { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public bool IsActive { get; set; }
        public Nullable<bool> HasError { get; set; }
        public string Error { get; set; }
    
        public virtual Org Org { get; set; }
    }
}
