//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestEwayService
{
    using System;
    using System.Collections.Generic;
    
    public partial class DailyAttendance
    {
        public int Id { get; set; }
        public Nullable<int> SptId { get; set; }
        public System.DateTime Date { get; set; }
        public Nullable<int> TotalBooking { get; set; }
        public Nullable<int> TotalAttended { get; set; }
        public Nullable<int> TotalAbsence { get; set; }
        public Nullable<int> TotalCasual { get; set; }
        public Nullable<int> SiteId { get; set; }
        public Nullable<int> ProgramCategoryId { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public string CreatedBy { get; set; }
        public string UpdatedBy { get; set; }
        public byte[] Version { get; set; }
        public Nullable<int> HoTermId { get; set; }
    }
}
