//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestEwayService
{
    using System;
    using System.Collections.Generic;
    
    public partial class FinancialHistory
    {
        public int Id { get; set; }
        public int OrgId { get; set; }
        public System.DateTime PeriodStart { get; set; }
        public System.DateTime PeriodEnd { get; set; }
        public Nullable<decimal> TotalIncomeGross { get; set; }
        public Nullable<decimal> GrossProfit { get; set; }
        public Nullable<decimal> TotalOperatingExpense { get; set; }
        public Nullable<decimal> TotalBankBalance { get; set; }
        public Nullable<decimal> NetProfit { get; set; }
        public Nullable<System.DateTime> XeroLastUpdated { get; set; }
        public System.DateTime LastUpdated { get; set; }
        public string LastUpdatedBy { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public byte[] Version { get; set; }
        public bool IsActive { get; set; }
    
        public virtual Org Org { get; set; }
    }
}
