//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestEwayService
{
    using System;
    using System.Collections.Generic;
    
    public partial class ImpersonateUserHistory
    {
        public int Id { get; set; }
        public int ImpersonatedUser { get; set; }
        public int ImpersonatedBy { get; set; }
        public System.DateTime ImpersonatedFrom { get; set; }
        public System.DateTime ImpersonatedTo { get; set; }
    
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
    }
}
