//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestEwayService
{
    using System;
    using System.Collections.Generic;
    
    public partial class InvoiceLine
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public InvoiceLine()
        {
            this.ChildDiscountHistoryLookups = new HashSet<ChildDiscountHistoryLookup>();
        }
    
        public int Id { get; set; }
        public int InvoiceId { get; set; }
        public Nullable<System.Guid> XeroLineItemId { get; set; }
        public string Description { get; set; }
        public Nullable<int> Quantity { get; set; }
        public decimal UnitPrice { get; set; }
        public decimal Amount { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime UpdatedOn { get; set; }
        public string UpdatedBy { get; set; }
        public bool IsActive { get; set; }
        public byte[] Version { get; set; }
        public Nullable<int> Booking_SptId { get; set; }
        public Nullable<int> ItemCodeId { get; set; }
        public Nullable<int> TrackingCatOptionId { get; set; }
        public Nullable<int> AdditionalInvRefId { get; set; }
    
        public virtual Booking_Spt Booking_Spt { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChildDiscountHistoryLookup> ChildDiscountHistoryLookups { get; set; }
        public virtual Invoice Invoice { get; set; }
        public virtual XeroItemCode XeroItemCode { get; set; }
        public virtual XeroTrackingCatOption XeroTrackingCatOption { get; set; }
    }
}
