//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestEwayService
{
    using System;
    using System.Collections.Generic;
    
    public partial class NotificationReminder
    {
        public int Id { get; set; }
        public string ModuleName { get; set; }
        public int ModuleId { get; set; }
        public Nullable<bool> FirstProcessed { get; set; }
        public Nullable<bool> SecondProcessed { get; set; }
        public Nullable<bool> ThirdProcessed { get; set; }
        public int DeliveryRule { get; set; }
        public Nullable<System.DateTime> LastProcessedOn { get; set; }
        public int SiteId { get; set; }
        public string Error { get; set; }
        public Nullable<int> RetryCount { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public string Source { get; set; }
        public string Reference { get; set; }
        public Nullable<bool> IsActive { get; set; }
    
        public virtual Org Org { get; set; }
    }
}
