//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestEwayService
{
    using System;
    using System.Collections.Generic;
    
    public partial class Org
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Org()
        {
            this.AchievementTrackings = new HashSet<AchievementTracking>();
            this.Activities = new HashSet<Activity>();
            this.BatchTimeSheets = new HashSet<BatchTimeSheet>();
            this.Billings = new HashSet<Billing>();
            this.Bookings = new HashSet<Booking>();
            this.BookingTemplates = new HashSet<BookingTemplate>();
            this.ChildDiscounts = new HashSet<ChildDiscount>();
            this.ContactGroups = new HashSet<ContactGroup>();
            this.CssBillingGroups = new HashSet<CssBillingGroup>();
            this.CssBillingGroup_Org = new HashSet<CssBillingGroup_Org>();
            this.CssCreditCardAccessCodes = new HashSet<CssCreditCardAccessCode>();
            this.CssInvoices = new HashSet<CssInvoice>();
            this.CssPaymentSetups = new HashSet<CssPaymentSetup>();
            this.CssSubscriptions = new HashSet<CssSubscription>();
            this.DashboardMessages = new HashSet<DashboardMessage>();
            this.ExcludeDays = new HashSet<ExcludeDay>();
            this.FinancialHistories = new HashSet<FinancialHistory>();
            this.FlyerTemplates = new HashSet<FlyerTemplate>();
            this.HeadCounts = new HashSet<HeadCount>();
            this.Media = new HashSet<Medium>();
            this.MessageHistories = new HashSet<MessageHistory>();
            this.NotificationInstances = new HashSet<NotificationInstance>();
            this.NotificationReminders = new HashSet<NotificationReminder>();
            this.Org_Child = new HashSet<Org_Child>();
            this.Org_Contact = new HashSet<Org_Contact>();
            this.Org_CSS_BillingRule = new HashSet<Org_CSS_BillingRule>();
            this.Org1 = new HashSet<Org>();
            this.Org_User = new HashSet<Org_User>();
            this.OrgCustomizes = new HashSet<OrgCustomize>();
            this.OrgDesigns = new HashSet<OrgDesign>();
            this.OrgNotificationSettings = new HashSet<OrgNotificationSetting>();
            this.OrgReferences = new HashSet<OrgReference>();
            this.OrgReferenceSettings = new HashSet<OrgReferenceSetting>();
            this.OrgTandCs = new HashSet<OrgTandC>();
            this.OscarCoCs = new HashSet<OscarCoC>();
            this.OscarDeclarations = new HashSet<OscarDeclaration>();
            this.OscarDelaration_Child = new HashSet<OscarDelaration_Child>();
            this.OscarSettings = new HashSet<OscarSetting>();
            this.OscarTracking_Child = new HashSet<OscarTracking_Child>();
            this.OscarTrackings = new HashSet<OscarTracking>();
            this.PaymentBatches = new HashSet<PaymentBatch>();
            this.PortfolioSettings = new HashSet<PortfolioSetting>();
            this.Programs = new HashSet<Program>();
            this.ProgramCategories = new HashSet<ProgramCategory>();
            this.PromoCodes = new HashSet<PromoCode>();
            this.PromoMsgTemplates = new HashSet<PromoMsgTemplate>();
            this.Reports = new HashSet<Report>();
            this.ReportSubscriptions = new HashSet<ReportSubscription>();
            this.School_Org = new HashSet<School_Org>();
            this.Sessions = new HashSet<Session>();
            this.Site_Program_Term = new HashSet<Site_Program_Term>();
            this.SiteDPSDetails = new HashSet<SiteDPSDetail>();
            this.SiteGroups = new HashSet<SiteGroup>();
            this.SiteNotes = new HashSet<SiteNote>();
            this.SitePaymentGateways = new HashSet<SitePaymentGateway>();
            this.SitePaymentMethods = new HashSet<SitePaymentMethod>();
            this.Spt_Instance = new HashSet<Spt_Instance>();
            this.StaffRosters = new HashSet<StaffRoster>();
            this.Terms = new HashSet<Term>();
            this.Territories = new HashSet<Territory>();
            this.TimeSheets = new HashSet<TimeSheet>();
            this.User_FavouriteSites = new HashSet<User_FavouriteSites>();
            this.UserOrgAccesses = new HashSet<UserOrgAccess>();
            this.XeroAccountCodes = new HashSet<XeroAccountCode>();
            this.XeroContacts = new HashSet<XeroContact>();
            this.XeroCreditNoteQueues = new HashSet<XeroCreditNoteQueue>();
            this.XeroEditBookingQueues = new HashSet<XeroEditBookingQueue>();
            this.XeroEditInvoiceQueues = new HashSet<XeroEditInvoiceQueue>();
            this.XeroInvoiceQueues = new HashSet<XeroInvoiceQueue>();
            this.XeroItemCodes = new HashSet<XeroItemCode>();
            this.XeroPaymentQueues = new HashSet<XeroPaymentQueue>();
            this.XeroProcessorStates = new HashSet<XeroProcessorState>();
            this.XeroSubsidyPaymentQueues = new HashSet<XeroSubsidyPaymentQueue>();
            this.XeroTrackingCategories = new HashSet<XeroTrackingCategory>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public Nullable<int> SchoolId { get; set; }
        public Nullable<int> OldId { get; set; }
        public string CompanyName { get; set; }
        public Nullable<int> TypeId { get; set; }
        public Nullable<int> ParentId { get; set; }
        public Nullable<int> TerritoryId { get; set; }
        public Nullable<int> ContactId { get; set; }
        public Nullable<int> Decile { get; set; }
        public Nullable<int> Roll { get; set; }
        public Nullable<int> RollApproved { get; set; }
        public Nullable<System.DateTime> LeaseStart { get; set; }
        public Nullable<System.DateTime> LeaseEnd { get; set; }
        public string LeasorName { get; set; }
        public Nullable<decimal> LeaseCostFixed { get; set; }
        public string MeetingRoom { get; set; }
        public string BankAccNum { get; set; }
        public string MsdNum { get; set; }
        public string OscarNum { get; set; }
        public string Comments { get; set; }
        public string ExtraChargeType { get; set; }
        public Nullable<decimal> ExtraMinRate { get; set; }
        public Nullable<int> BeforeThreshold { get; set; }
        public Nullable<int> AfterThreshold { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public System.DateTime UpdateOn { get; set; }
        public string CreatedBy { get; set; }
        public string UpdatedBy { get; set; }
        public bool IsActive { get; set; }
        public bool HasSaved { get; set; }
        public byte[] Version { get; set; }
        public Nullable<System.DateTime> LicenceStart { get; set; }
        public Nullable<System.DateTime> LicenceEnd { get; set; }
        public Nullable<decimal> WeeklyAdminCost { get; set; }
        public Nullable<decimal> WeeklyRentCost { get; set; }
        public Nullable<decimal> CurrentRevenue { get; set; }
        public Nullable<decimal> CurrentExpenses { get; set; }
        public Nullable<decimal> CurrentBalance { get; set; }
        public Nullable<decimal> CurrentOverdueAmt { get; set; }
        public string MasterPin { get; set; }
        public Nullable<bool> IsChildPhotoEnabled { get; set; }
        public Nullable<bool> IsAuthPhotoEnabled { get; set; }
        public Nullable<bool> IsStaffPhotoEnabled { get; set; }
        public Nullable<bool> IsMultiSitePickupEnabled { get; set; }
        public Nullable<bool> IsFreeTrial { get; set; }
        public Nullable<System.DateTime> ExpiryDate { get; set; }
        public string StaffClockMethod { get; set; }
        public Nullable<int> LeaseCostPercentage { get; set; }
        public Nullable<bool> IsPaymentGatewayEnabled { get; set; }
        public string SiteBankAccNum { get; set; }
        public Nullable<bool> IsDashboardMsgEnabled { get; set; }
        public Nullable<bool> IsEMailMsgEnabled { get; set; }
        public Nullable<bool> IsSMSMsgEnabled { get; set; }
        public string SiteContactPersone { get; set; }
        public string SiteContactPhone { get; set; }
        public string SiteContactEmail { get; set; }
        public bool InvoiceDateSetting { get; set; }
        public string HeadOfficeLogo { get; set; }
        public Nullable<bool> IsWizard { get; set; }
        public Nullable<int> LastStep { get; set; }
        public Nullable<bool> IsProgrammePriceVisible { get; set; }
        public Nullable<bool> IsBookingPromoMsgVisible { get; set; }
        public string BookingPromotionMsg { get; set; }
        public Nullable<bool> IsHolBookingPromoMsgVisible { get; set; }
        public string HolBookingPromoMsg { get; set; }
        public Nullable<bool> IsSpecialBookingPromoMsgVisible { get; set; }
        public string SpecialBookingPromoMsg { get; set; }
        public string LoginURL { get; set; }
        public bool ShowCustomisedBooking { get; set; }
        public int InvoiceGenDay { get; set; }
        public int InvoiceGenWeek { get; set; }
        public int InvoiceDueDay { get; set; }
        public int InvoiceDueWeek { get; set; }
        public Nullable<int> InvoiceDay { get; set; }
        public Nullable<int> InvoiceDueDays { get; set; }
        public Nullable<bool> IsInvArrearBasedOnStart { get; set; }
        public Nullable<decimal> LicenceFee { get; set; }
        public Nullable<int> CSSBillingPlanId { get; set; }
        public Nullable<System.DateTime> CSSRevireDate { get; set; }
        public string CSSComment { get; set; }
        public string BookingInfoRegular { get; set; }
        public string BookingInfoCasual { get; set; }
        public Nullable<bool> IsNew { get; set; }
        public Nullable<int> CurrentStatus { get; set; }
        public string Logo { get; set; }
        public Nullable<bool> AllowOverdueNotification { get; set; }
        public Nullable<bool> IsCreditCardPaymentDisabled { get; set; }
        public Nullable<int> NewChildFlagDays { get; set; }
        public Nullable<bool> ExclusionDayIsChargeable { get; set; }
        public Nullable<bool> IsAimyClient { get; set; }
        public Nullable<bool> CustomisedBookingCalendarReadOnly { get; set; }
        public Nullable<bool> ShowParentDOB { get; set; }
        public Nullable<bool> IsMergeReconcilInvoice { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AchievementTracking> AchievementTrackings { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Activity> Activities { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BatchTimeSheet> BatchTimeSheets { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Billing> Billings { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Booking> Bookings { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BookingTemplate> BookingTemplates { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChildDiscount> ChildDiscounts { get; set; }
        public virtual Contact Contact { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ContactGroup> ContactGroups { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CssBillingGroup> CssBillingGroups { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CssBillingGroup_Org> CssBillingGroup_Org { get; set; }
        public virtual CssBillingPlan CssBillingPlan { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CssCreditCardAccessCode> CssCreditCardAccessCodes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CssInvoice> CssInvoices { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CssPaymentSetup> CssPaymentSetups { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CssSubscription> CssSubscriptions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DashboardMessage> DashboardMessages { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ExcludeDay> ExcludeDays { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FinancialHistory> FinancialHistories { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FlyerTemplate> FlyerTemplates { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HeadCount> HeadCounts { get; set; }
        public virtual Lookup Lookup { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Medium> Media { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MessageHistory> MessageHistories { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NotificationInstance> NotificationInstances { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NotificationReminder> NotificationReminders { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Org_Child> Org_Child { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Org_Contact> Org_Contact { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Org_CSS_BillingRule> Org_CSS_BillingRule { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Org> Org1 { get; set; }
        public virtual Org Org2 { get; set; }
        public virtual School School { get; set; }
        public virtual Territory Territory { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Org_User> Org_User { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrgCustomize> OrgCustomizes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrgDesign> OrgDesigns { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrgNotificationSetting> OrgNotificationSettings { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrgReference> OrgReferences { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrgReferenceSetting> OrgReferenceSettings { get; set; }
        public virtual OrgSetting OrgSetting { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrgTandC> OrgTandCs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OscarCoC> OscarCoCs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OscarDeclaration> OscarDeclarations { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OscarDelaration_Child> OscarDelaration_Child { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OscarSetting> OscarSettings { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OscarTracking_Child> OscarTracking_Child { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OscarTracking> OscarTrackings { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PaymentBatch> PaymentBatches { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PortfolioSetting> PortfolioSettings { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Program> Programs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProgramCategory> ProgramCategories { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PromoCode> PromoCodes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PromoMsgTemplate> PromoMsgTemplates { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Report> Reports { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ReportSubscription> ReportSubscriptions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<School_Org> School_Org { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Session> Sessions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Site_Program_Term> Site_Program_Term { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SiteDPSDetail> SiteDPSDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SiteGroup> SiteGroups { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SiteNote> SiteNotes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SitePaymentGateway> SitePaymentGateways { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SitePaymentMethod> SitePaymentMethods { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Spt_Instance> Spt_Instance { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StaffRoster> StaffRosters { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Term> Terms { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Territory> Territories { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TimeSheet> TimeSheets { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<User_FavouriteSites> User_FavouriteSites { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserOrgAccess> UserOrgAccesses { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<XeroAccountCode> XeroAccountCodes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<XeroContact> XeroContacts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<XeroCreditNoteQueue> XeroCreditNoteQueues { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<XeroEditBookingQueue> XeroEditBookingQueues { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<XeroEditInvoiceQueue> XeroEditInvoiceQueues { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<XeroInvoiceQueue> XeroInvoiceQueues { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<XeroItemCode> XeroItemCodes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<XeroPaymentQueue> XeroPaymentQueues { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<XeroProcessorState> XeroProcessorStates { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<XeroSubsidyPaymentQueue> XeroSubsidyPaymentQueues { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<XeroTrackingCategory> XeroTrackingCategories { get; set; }
    }
}
