//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestEwayService
{
    using System;
    using System.Collections.Generic;
    
    public partial class Org_CSS_BillingRule
    {
        public int Id { get; set; }
        public Nullable<int> OrgId { get; set; }
        public Nullable<int> BillingRuleId { get; set; }
        public string RuleName { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public Nullable<int> Percentage { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public string Comment { get; set; }
        public string CreatedBy { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> CreratedOn { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public byte[] Version { get; set; }
        public Nullable<bool> IsActive { get; set; }
    
        public virtual CssBillingRule CssBillingRule { get; set; }
        public virtual Org Org { get; set; }
    }
}
