//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestEwayService
{
    using System;
    using System.Collections.Generic;
    
    public partial class OscarRenewalFormTracking
    {
        public int Id { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<int> SiteId { get; set; }
        public Nullable<System.DateTime> CurrentReviewDate { get; set; }
        public Nullable<System.DateTime> ReactivationDate { get; set; }
        public bool Stage1 { get; set; }
        public Nullable<System.DateTime> Stage1Date { get; set; }
        public bool Stage2 { get; set; }
        public Nullable<System.DateTime> Stage2Date { get; set; }
        public bool Stage3 { get; set; }
        public Nullable<System.DateTime> Stage3Date { get; set; }
        public bool Stage4 { get; set; }
        public Nullable<System.DateTime> Stage4Date { get; set; }
        public bool Submitted { get; set; }
        public Nullable<System.DateTime> SubmittedDate { get; set; }
        public string Note { get; set; }
        public string Email { get; set; }
        public bool IsActive { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public string UpdatedBy { get; set; }
        public bool IsCompleted { get; set; }
        public Nullable<bool> IsDeclined { get; set; }
        public Nullable<bool> IsNewApplication { get; set; }
    }
}
