//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestEwayService
{
    using System;
    using System.Collections.Generic;
    
    public partial class OscarCoC
    {
        public int Id { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<int> SiteId { get; set; }
        public bool IsRequired { get; set; }
        public bool FormSent { get; set; }
        public Nullable<System.DateTime> FormSentDate { get; set; }
        public bool FormRecieved { get; set; }
        public Nullable<System.DateTime> FormReceivedDate { get; set; }
        public bool FormLodged { get; set; }
        public Nullable<System.DateTime> FormLodgedDate { get; set; }
        public bool IsVerified { get; set; }
        public Nullable<System.DateTime> VerifiedDate { get; set; }
        public bool IsCompleted { get; set; }
        public bool IsDeclined { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime UpdatedOn { get; set; }
        public string UpdatedBy { get; set; }
        public string Email { get; set; }
        public string Note { get; set; }
        public Nullable<bool> IsNewApplication { get; set; }
    
        public virtual Org Org { get; set; }
        public virtual User User { get; set; }
    }
}
