//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestEwayService
{
    using System;
    using System.Collections.Generic;
    
    public partial class OutgoingMessage
    {
        public int Id { get; set; }
        public int UserID { get; set; }
        public Nullable<int> NumberOfSMS { get; set; }
        public string Subject { get; set; }
        public string Reference { get; set; }
        public string AttachmentFilePath { get; set; }
        public string Data { get; set; }
        public string DeliveryMethod { get; set; }
        public string RecipientEmail { get; set; }
        public string RecipientMobile { get; set; }
        public bool IsProcessed { get; set; }
        public Nullable<System.DateTime> ProcessedOn { get; set; }
        public string Error { get; set; }
        public int RetryCount { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public byte[] Version { get; set; }
        public string Source { get; set; }
        public string ReplyEmail { get; set; }
    
        public virtual User User { get; set; }
    }
}
