//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestEwayService
{
    using System;
    using System.Collections.Generic;
    
    public partial class Payment
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Payment()
        {
            this.XeroPaymentQueues = new HashSet<XeroPaymentQueue>();
        }
    
        public int Id { get; set; }
        public int PaymentBatchId { get; set; }
        public Nullable<int> SiteId { get; set; }
        public Nullable<int> InvoiceId { get; set; }
        public int XeroStatusId { get; set; }
        public int BillingId { get; set; }
        public Nullable<System.Guid> XeroTransactionId { get; set; }
        public decimal PaidAmount { get; set; }
        public bool Error { get; set; }
        public string ErrorDescription { get; set; }
        public Nullable<System.DateTime> XeroLastUpdatedUTC { get; set; }
        public bool IsActive { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime UpdatedOn { get; set; }
        public string UpdatedBy { get; set; }
        public byte[] Version { get; set; }
    
        public virtual Billing Billing { get; set; }
        public virtual Invoice Invoice { get; set; }
        public virtual Lookup Lookup { get; set; }
        public virtual PaymentBatch PaymentBatch { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<XeroPaymentQueue> XeroPaymentQueues { get; set; }
    }
}
