//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestEwayService
{
    using System;
    using System.Collections.Generic;
    
    public partial class SiteGroup_Booking_Spt
    {
        public int Id { get; set; }
        public int SiteGroupId { get; set; }
        public int Booking_SptId { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedOn { get; set; }
    
        public virtual Booking_Spt Booking_Spt { get; set; }
        public virtual SiteGroup SiteGroup { get; set; }
    }
}
