//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestEwayService
{
    using System;
    using System.Collections.Generic;
    
    public partial class SitePaymentMethod
    {
        public int Id { get; set; }
        public int SiteId { get; set; }
        public Nullable<int> TypeId { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public string BankInfo { get; set; }
        public string BankAccountNumber { get; set; }
        public string DirectDebitForm { get; set; }
    
        public virtual Org Org { get; set; }
    }
}
