//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestEwayService
{
    using System;
    using System.Collections.Generic;
    
    public partial class Spt_Session
    {
        public int Id { get; set; }
        public int SptId { get; set; }
        public Nullable<System.TimeSpan> StartTime { get; set; }
        public Nullable<System.TimeSpan> EndTime { get; set; }
        public Nullable<decimal> Rate { get; set; }
        public Nullable<int> ItemCode { get; set; }
        public bool IsActive { get; set; }
    
        public virtual Site_Program_Term Site_Program_Term { get; set; }
    }
}
