//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestEwayService
{
    using System;
    using System.Collections.Generic;
    
    public partial class SubsidyPayment
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SubsidyPayment()
        {
            this.XeroSubsidyPaymentQueues = new HashSet<XeroSubsidyPaymentQueue>();
        }
    
        public int Id { get; set; }
        public Nullable<int> InvoiceId { get; set; }
        public Nullable<int> SubsidyId { get; set; }
        public Nullable<int> XeroAccCodeId { get; set; }
        public Nullable<int> StatusId { get; set; }
        public Nullable<int> ExternalInvId { get; set; }
        public Nullable<System.Guid> XeroTransactionId { get; set; }
        public string Email { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public System.DateTime StartDate { get; set; }
        public System.DateTime EndDate { get; set; }
        public System.DateTime PaymentDate { get; set; }
        public string PaymentType { get; set; }
        public string InvoiceReference { get; set; }
        public decimal Amount { get; set; }
        public string SubsidyPaymentReference { get; set; }
        public Nullable<int> SubsidyPaymentIndexId { get; set; }
        public Nullable<System.DateTime> XeroUpdatedDateUTC { get; set; }
        public Nullable<bool> Error { get; set; }
        public string ErrorDescription { get; set; }
        public bool HasAdded { get; set; }
        public bool IsActive { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public string UpdatedBy { get; set; }
        public System.DateTime UpdatedOn { get; set; }
        public byte[] Version { get; set; }
    
        public virtual Invoice Invoice { get; set; }
        public virtual Lookup Lookup { get; set; }
        public virtual Subsidy Subsidy { get; set; }
        public virtual SubsidyPaymentIndex SubsidyPaymentIndex { get; set; }
        public virtual XeroAccountCode XeroAccountCode { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<XeroSubsidyPaymentQueue> XeroSubsidyPaymentQueues { get; set; }
    }
}
