//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestEwayService
{
    using System;
    using System.Collections.Generic;
    
    public partial class TempManualPayment
    {
        public int Id { get; set; }
        public System.DateTime Date { get; set; }
        public decimal Amout { get; set; }
        public int InvoiceId { get; set; }
        public string ParentName { get; set; }
        public string OrgName { get; set; }
        public Nullable<int> ParentId { get; set; }
        public Nullable<int> OrgId { get; set; }
    }
}
