//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestEwayService
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public User()
        {
            this.Attendances = new HashSet<Attendance>();
            this.Attendance_Portfolio = new HashSet<Attendance_Portfolio>();
            this.Billings = new HashSet<Billing>();
            this.Bookings = new HashSet<Booking>();
            this.BookingAudits = new HashSet<BookingAudit>();
            this.BookingTemplateQueues = new HashSet<BookingTemplateQueue>();
            this.ContactGroups = new HashSet<ContactGroup>();
            this.DashboardViewHistories = new HashSet<DashboardViewHistory>();
            this.DefaultBillingDiscounts = new HashSet<DefaultBillingDiscount>();
            this.EventDurations = new HashSet<EventDuration>();
            this.ImpersonateUserHistories = new HashSet<ImpersonateUserHistory>();
            this.ImpersonateUserHistories1 = new HashSet<ImpersonateUserHistory>();
            this.MessageHistories = new HashSet<MessageHistory>();
            this.Notification_User = new HashSet<Notification_User>();
            this.NotificationInstances = new HashSet<NotificationInstance>();
            this.Org_User = new HashSet<Org_User>();
            this.OscarCoCs = new HashSet<OscarCoC>();
            this.OscarDeclarations = new HashSet<OscarDeclaration>();
            this.OscarDelaration_Child = new HashSet<OscarDelaration_Child>();
            this.OscarTrackings = new HashSet<OscarTracking>();
            this.OscarTracking_Child = new HashSet<OscarTracking_Child>();
            this.OutgoingMessages = new HashSet<OutgoingMessage>();
            this.PaymentBatches = new HashSet<PaymentBatch>();
            this.PromoCodes = new HashSet<PromoCode>();
            this.PromoCodeUsages = new HashSet<PromoCodeUsage>();
            this.QrCodes = new HashSet<QrCode>();
            this.Site_Program_Term = new HashSet<Site_Program_Term>();
            this.StaffAvailabilities = new HashSet<StaffAvailability>();
            this.StaffClocks = new HashSet<StaffClock>();
            this.StaffRosters = new HashSet<StaffRoster>();
            this.Subsidies = new HashSet<Subsidy>();
            this.Timelines = new HashSet<Timeline>();
            this.TimeSheets = new HashSet<TimeSheet>();
            this.User_Child = new HashSet<User_Child>();
            this.User_Contact = new HashSet<User_Contact>();
            this.User_FavouriteSites = new HashSet<User_FavouriteSites>();
            this.User_Message = new HashSet<User_Message>();
            this.User_OscarSetting = new HashSet<User_OscarSetting>();
            this.User_Permission = new HashSet<User_Permission>();
            this.UserOrgAccesses = new HashSet<UserOrgAccess>();
            this.XeroInvoices = new HashSet<XeroInvoice>();
        }
    
        public int Id { get; set; }
        public Nullable<long> EwayCustomerId { get; set; }
        public string Username { get; set; }
        public string Email { get; set; }
        public Nullable<int> ContactId { get; set; }
        public int RoleId { get; set; }
        public string Password { get; set; }
        public string PasswordHash { get; set; }
        public bool CanLogin { get; set; }
        public string EmailConfirmationToken { get; set; }
        public Nullable<bool> IsEmailConfirmationValid { get; set; }
        public string PasswordResetToken { get; set; }
        public Nullable<bool> IsPswResetTokenValid { get; set; }
        public bool IsAdmin { get; set; }
        public Nullable<System.DateTime> StaffPayrollLatSyncOn { get; set; }
        public Nullable<decimal> StaffCostPerHour { get; set; }
        public Nullable<int> TotalHoursToBeSync { get; set; }
        public string Colour { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public System.DateTime UpdatedOn { get; set; }
        public string CreatedBy { get; set; }
        public string UpdatedBy { get; set; }
        public bool IsActive { get; set; }
        public byte[] Version { get; set; }
        public string PinCode { get; set; }
        public bool IsOrgAdmin { get; set; }
        public Nullable<System.DateTime> WorkStartDate { get; set; }
        public Nullable<System.DateTime> WorkEndDate { get; set; }
        public Nullable<int> CurrentOrgId { get; set; }
        public Nullable<System.DateTime> LastLogedOn { get; set; }
        public Nullable<int> RetryAttempt { get; set; }
        public bool SysAdmin { get; set; }
        public string Title { get; set; }
        public string PasswordBackup { get; set; }
        public string EmployeeId { get; set; }
        public Nullable<bool> QuickRegistered { get; set; }
        public Nullable<bool> RequiredPasswordChange { get; set; }
        public Nullable<bool> IsKPFClient { get; set; }
        public Nullable<bool> IsAimyClient { get; set; }
        public Nullable<bool> IsIncompleteProfile { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Attendance> Attendances { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Attendance_Portfolio> Attendance_Portfolio { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Billing> Billings { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Booking> Bookings { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BookingAudit> BookingAudits { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BookingTemplateQueue> BookingTemplateQueues { get; set; }
        public virtual Contact Contact { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ContactGroup> ContactGroups { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DashboardViewHistory> DashboardViewHistories { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DefaultBillingDiscount> DefaultBillingDiscounts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EventDuration> EventDurations { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ImpersonateUserHistory> ImpersonateUserHistories { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ImpersonateUserHistory> ImpersonateUserHistories1 { get; set; }
        public virtual Lookup Lookup { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MessageHistory> MessageHistories { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Notification_User> Notification_User { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NotificationInstance> NotificationInstances { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Org_User> Org_User { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OscarCoC> OscarCoCs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OscarDeclaration> OscarDeclarations { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OscarDelaration_Child> OscarDelaration_Child { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OscarTracking> OscarTrackings { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OscarTracking_Child> OscarTracking_Child { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OutgoingMessage> OutgoingMessages { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PaymentBatch> PaymentBatches { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PromoCode> PromoCodes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PromoCodeUsage> PromoCodeUsages { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<QrCode> QrCodes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Site_Program_Term> Site_Program_Term { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StaffAvailability> StaffAvailabilities { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StaffClock> StaffClocks { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StaffRoster> StaffRosters { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Subsidy> Subsidies { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Timeline> Timelines { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TimeSheet> TimeSheets { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<User_Child> User_Child { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<User_Contact> User_Contact { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<User_FavouriteSites> User_FavouriteSites { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<User_Message> User_Message { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<User_OscarSetting> User_OscarSetting { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<User_Permission> User_Permission { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserOrgAccess> UserOrgAccesses { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<XeroInvoice> XeroInvoices { get; set; }
    }
}
