//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestEwayService
{
    using System;
    using System.Collections.Generic;
    
    public partial class XeroInvoiceLine
    {
        public int Id { get; set; }
        public int XeroInvoiceId { get; set; }
        public System.Guid XeroLineItemId { get; set; }
        public string Description { get; set; }
        public int Quantity { get; set; }
        public decimal UnitPrice { get; set; }
        public decimal Amount { get; set; }
        public string ItemCode { get; set; }
        public string AccCode { get; set; }
        public string ProgTrackingCode { get; set; }
        public string SiteTrackingCode { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public System.DateTime UpdatedOn { get; set; }
        public bool IsActive { get; set; }
        public byte[] Version { get; set; }
    
        public virtual XeroInvoice XeroInvoice { get; set; }
    }
}
