//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestEwayService
{
    using System;
    using System.Collections.Generic;
    
    public partial class XeroEditBookingQueue
    {
        public int Id { get; set; }
        public int OrgId { get; set; }
        public int BillingId { get; set; }
        public bool IsProcessed { get; set; }
        public System.DateTime LastUpdated { get; set; }
    
        public virtual Billing Billing { get; set; }
        public virtual Org Org { get; set; }
    }
}
